#!/usr/bin/env python3
"""
Build script to create pboo.bundle.js by combining:
- widget.html (as WIDGET_MARKUP)
- styles.css (as WIDGET_STYLES)
- pboo.js (the loader code)
"""

from pathlib import Path
import sys


def main():
    widget_dir = Path(__file__).parent / "server" / "widget"

    # Read widget files
    try:
        markup_path = widget_dir / "widget.html"
        styles_path = widget_dir / "styles.css"
        pboo_path = widget_dir / "pboo.js"

        with open(markup_path, "r") as f:
            markup = f.read()

        with open(styles_path, "r") as f:
            styles = f.read()

        with open(pboo_path, "r") as f:
            pboo_code = f.read()
    except FileNotFoundError as e:
        print(f"Error: Could not find widget file: {e}")
        sys.exit(1)

    # Escape strings for JavaScript
    markup_escaped = markup.replace("\\", "\\\\").replace(
        "`", "\\`").replace("$", "\\$")
    styles_escaped = styles.replace("\\", "\\\\").replace(
        "`", "\\`").replace("$", "\\$")

    # Generate bundle
    bundle = f'''// Peekaboo Widget Bundle
// Generated by build_widget.py
// Contains: widget.html, styles.css, and pboo.js

window.WIDGET_MARKUP = `{markup_escaped}`;

window.WIDGET_STYLES = `{styles_escaped}`;

// Peekaboo Loader
{pboo_code}
'''

    # Write bundle
    bundle_path = widget_dir / "pboo.bundle.js"
    with open(bundle_path, "w") as f:
        f.write(bundle)

    bundle_size = len(bundle) / 1024  # KB
    print(f"✅ Built {bundle_path.name} ({bundle_size:.1f} KB)")
    print(f"   - widget.html: {len(markup)} bytes")
    print(f"   - styles.css: {len(styles)} bytes")
    print(f"   - pboo.js: {len(pboo_code)} bytes")


if __name__ == "__main__":
    main()
