services:
  - type: web
    name: peekaboo-server
    runtime: docker
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: PUBLIC_BASE_URL
        value: https://peekaboo-477i.onrender.com
