create table if not exists public.sites (
  id bigint generated by default as identity primary key,
  site_id text unique not null,
  operator_token_hash text not null,
  allowed_origin text,
  created_at timestamptz not null default now()
);

alter table public.sites add column if not exists allowed_origin text;

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  conversation_id text unique not null,
  site_id text not null references public.sites(site_id) on delete cascade,
  visitor_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id text not null references public.conversations(conversation_id) on delete cascade,
  sender text not null check (sender in ('visitor', 'operator')),
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists conversations_site_id_idx on public.conversations(site_id);
create index if not exists messages_conversation_id_idx on public.messages(conversation_id);

alter table public.sites enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
