create table if not exists public.sites (
  id bigint generated by default as identity primary key,
  site_id text unique not null,
  owner_id uuid,
  operator_token_hash text not null,
  allowed_origin text,
  created_at timestamptz not null default now()
);

alter table public.sites add column if not exists allowed_origin text;
alter table public.sites add column if not exists owner_id uuid;

create table if not exists public.owner_api_keys (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  key_hash text unique not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  conversation_id text unique not null,
  site_id text not null references public.sites(site_id) on delete cascade,
  visitor_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id text not null references public.conversations(conversation_id) on delete cascade,
  sender text not null check (sender in ('visitor', 'operator')),
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists conversations_site_id_idx on public.conversations(site_id);
create index if not exists messages_conversation_id_idx on public.messages(conversation_id);
create index if not exists sites_owner_id_idx on public.sites(owner_id);
create index if not exists owner_api_keys_owner_id_idx on public.owner_api_keys(owner_id);
create index if not exists owner_api_keys_key_hash_idx on public.owner_api_keys(key_hash);

alter table public.sites enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.owner_api_keys enable row level security;
