create table if not exists public.sites (
  id bigint generated by default as identity primary key,
  site_id text unique not null,
  owner_id uuid,
  operator_token_hash text not null,
  allowed_origin text,
  created_at timestamptz not null default now()
);

alter table public.sites add column if not exists allowed_origin text;
alter table public.sites add column if not exists owner_id uuid;

create table if not exists public.owner_api_keys (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  key_hash text unique not null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  conversation_id text unique not null,
  site_id text not null references public.sites(site_id) on delete cascade,
  visitor_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id text not null references public.conversations(conversation_id) on delete cascade,
  sender text not null check (sender in ('visitor', 'operator')),
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists conversations_site_id_idx on public.conversations(site_id);
create index if not exists messages_conversation_id_idx on public.messages(conversation_id);
create index if not exists sites_owner_id_idx on public.sites(owner_id);
create index if not exists owner_api_keys_owner_id_idx on public.owner_api_keys(owner_id);
create index if not exists owner_api_keys_key_hash_idx on public.owner_api_keys(key_hash);

alter table public.sites enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.owner_api_keys enable row level security;

-- The server connects with the service role key (SUPABASE_SECRET_KEY /
-- sb_secret_...), which bypasses row level security, so the tables above
-- deliberately define no policies for the anon role: a public client must not
-- be able to read or write site/owner data directly. All access flows through
-- the server, which authenticates owners by API key.

-- Remove the previously-created broad INSERT policy ("Allow key inserts") that
-- lets anyone (anon) mint owner API keys. It is a security hole and not needed:
-- the server inserts through the service role, which bypasses RLS regardless.
drop policy if exists "Allow key inserts" on public.owner_api_keys;

-- Also remove any dashboard-created policies that open these tables to the
-- anon/authenticated roles. A table with RLS enabled and no policies denies all
-- non-service-role access, which is the intended state: only the server (service
-- role, RLS-bypassing) touches site, owner, and message data.
drop policy if exists "Enable read access for all users" on public.sites;
drop policy if exists "Enable insert for authenticated users only" on public.sites;
drop policy if exists "Enable read access for all users" on public.owner_api_keys;
drop policy if exists "Enable insert for authenticated users only" on public.owner_api_keys;
drop policy if exists "Enable read access for all users" on public.messages;
drop policy if exists "Enable insert for authenticated users only" on public.messages;
drop policy if exists "Enable read access for all users" on public.conversations;
drop policy if exists "Enable insert for authenticated users only" on public.conversations;

-- ============================================================
-- Peekaboo v2 schema additions
-- ============================================================

-- sites: allow an allowlist of origins + widget config
alter table public.sites add column if not exists allowed_origins jsonb;
alter table public.sites add column if not exists widget_config jsonb;

-- conversations: add thread routing (no message bodies are stored)
alter table public.conversations add column if not exists telegram_thread_id text;
alter table public.conversations add column if not exists last_activity_at timestamptz default now();

create table if not exists public.integrations (
  id bigint generated by default as identity primary key,
  site_id text not null references public.sites(site_id) on delete cascade,
  provider text not null,
  destination_id text,
  credentials text not null,
  webhook_secret text,
  enabled boolean not null default true,
  config jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists integrations_site_id_idx on public.integrations(site_id);

create table if not exists public.pending_replies (
  id bigint generated by default as identity primary key,
  conversation_id text not null references public.conversations(conversation_id) on delete cascade,
  reply text not null,
  created_at timestamptz not null default now()
);
create index if not exists pending_replies_conversation_idx on public.pending_replies(conversation_id);

create table if not exists public.site_stats (
  site_id text primary key references public.sites(site_id) on delete cascade,
  messages_received bigint not null default 0,
  replies_sent bigint not null default 0,
  last_message_at timestamptz
);

-- RLS: deny anon/authenticated direct access; only the server (service role)
-- touches these tables. Every new table starts locked with no policies.
alter table public.integrations enable row level security;
alter table public.pending_replies enable row level security;
alter table public.site_stats enable row level security;
select 1;
